Созданы page's и index.php для applications
spectator196/mysite.local pull request #2
Opened 2023-04-05 17:17 UTC by spectator196

fix: исправлена ссылка на страницу /page в index.php для /managers.
build: созданы /page для /managers и /applications и index.php для applications.
refactor: переработан метод в get_db_info.php, теперь для каждой выгрузки имеется соответствующая функция.
build: созданы функции для получения информации о конкретных заявках/уч.записей менеджеров.
build: созданы функции для получения частичной информации о всех заявках/уч.записей менеджеров для создания таблицы.

2023-04-06 06:51 UTC, nuberry requested changes

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +        ],
А чем поле `sex` отличается от `reg_form`.
Ведь можно завести константу, например `SEX_ALLOWED_VALUES`.

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +    $correct_d_day_value=implode('.',$b_day_correct_list);
Что-то очень сложное и непредсказуемое и может сломаться.
Посмотри в сторону функции `date()`.

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
>      $mysql_link = new mysqli('127.0.0.1', 'root', '', 'db_mysite.local');
1) Формирование объекта `$mysql_link` можно вынести в отдельную функцию и возвращать оттуда объект.
Вот так объяви функцию `function get_mysql_link(): object{}`.

2) Вместо
```
if ($mysql_link == false) {
        print("Ошибка: Невозможно подключиться к MySQL " . mysqli_connect_error());
        return;
    }
```
воспользуйся
```
if ($mysql_link == false) {
        throw new \Exception("Ошибка: Невозможно подключиться к MySQL " . mysqli_connect_error());
    }
```

пустой `return` запрещен, т.к. в одной функции не может быть `void` и `object` одновременно, т.к. объявив типизацию в п.1 у тебя будет ошибка

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +function get_db_full_table_applications()
Добавь типизацию возвращаемого значения.
`function get_db_full_table_applications(): array`

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +function get_db_full_table_managers()
Аналогично добавь типизацию возвращаемого значения.
function get_db_full_table_managers(): array

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +    }
Аналогично. См комментарий про отдельную функцию выше

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
>          return;
Аналогично.
Запрещен `return` у тебя добавляется типизация в виде массива.
И добавь throw вместо `print` и `return`

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +        return;
Аналогично.
См. комментарии выше

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +    }
Аналогично.
См. комментарии выше

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +    }
Аналогично.
См. комментарии выше

2023-04-06 06:51 UTC, nuberry commented on index.php
> +  <p><a href="/managers/">• Менеджеры.</a></p>
Если хочешь список, то вместо `p` используй  списки `ul>li`

2023-04-06 06:51 UTC, nuberry commented on managers/index.php
> +include dirname(__DIR__, 1) . '\get_db_info.php';
Добавь подключение `config.php `.
Также `config.php` добавь в .gitignore

Подключить конфигурацию можно в `get_db_info.php` в иных местах тебе он не пригодится, пока что.

2023-04-06 06:51 UTC, nuberry commented on managers/page.php
> +include dirname(__DIR__, 1) . '\get_db_info.php';
Аналогично про `config.php`

2023-04-06 06:51 UTC, nuberry commented on applications/index.php
>  include dirname(__DIR__, 1) . '\get_db_info.php';
Аналогично про `config.php`

2023-04-06 06:51 UTC, nuberry commented on managers/index.php
> +    <td><a href=<?php print("/managers/page.php?manager_id=".$record['manager_id'])?>><?php print($record['full_name'])?></a></td>
Я приводил пример, что не надо использовать `print` для всего адреса. Ты лишь убрал домен, а `print` оставил.
Вот мой пример из ТГ
"значение `href`  можно сделать таким: `"/managers/page?id<?php print $record['id'];?>"`"

2023-04-06 06:51 UTC, nuberry commented on applications/index.php
> +    <td><a href=<?php print("/applications/page.php?id=".$record['id'])?>><?php print($record['full_name'])?></a></td>
Аналогично

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +    $sql_request = 'SELECT id, full_name FROM applications';
А почему убрал `*`? В чем разница м/д `*` и указанием полей

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +function get_db_specific_application($id)
Аналогично добавь типизацию возвращаемого значения.
`function get_db_specific_application(): array`

2023-04-06 06:51 UTC, nuberry commented on get_db_info.php
> +function get_db_specific_managers($manager_id)
Аналогично добавь типизацию возвращаемого значения.
`function get_db_specific_managers(): array`

2023-04-06 09:11 UTC, spectator196 commented on get_db_info.php
>      $mysql_link = new mysqli('127.0.0.1', 'root', '', 'db_mysite.local');
Модифицирован предложенный способ: 

```
function get_mysql_data($sql_request): object
{
    $mysql_link = new mysqli('127.0.0.1', 'root', '', 'db_mysite.local');
    if ($mysql_link == false) {
        throw new \Exception("Ошибка: Невозможно подключиться к MySQL " . mysqli_connect_error());
    }
    
    $result = mysqli_query($mysql_link, $sql_request);

    if ($result == false) {
        throw new \Exception("Произошла ошибка при выполнении запроса!");
    }

    return $result;
}
```

2023-04-06 09:50 UTC, spectator196 commented on get_db_info.php
> +    $correct_d_day_value=implode('.',$b_day_correct_list);
Исправлено следующим образом: 

```
    $db_b_day_data = DateTime::createFromFormat('Y-m-d', $data_list['b_day']);
    $correct_b_day_value = $db_b_day_data->format('m.d.Y');
```

2023-04-06 09:59 UTC, spectator196 commented on get_db_info.php
> +    $sql_request = 'SELECT id, full_name FROM applications';
Большая нагрузка на БД при использовании *.
Мне нужны только 2 столбца из БД, остальные данные излишни.

2023-04-09 09:28 UTC, nuberry reviewed
В целом неплохо, но есть замечания.

Не увидел добавления/редактирования/удаления для заявок

2023-04-09 09:28 UTC, nuberry commented on managers/edit.php
> +<?php endif; ?>
А это зачем? Полагаю это можно удалить

2023-04-09 09:28 UTC, nuberry commented on managers/add.php
> +<?php endif; ?>
А это зачем? Полагаю это можно удалить

2023-04-09 09:28 UTC, nuberry commented on managers/add.php
> +        </caption>
`caption` не в тему. Оставь просто `h1`

2023-04-09 09:28 UTC, nuberry commented on managers/page.php
> +  </caption>
`caption` не в тему. Оставь просто `h1`

2023-04-09 09:28 UTC, nuberry commented on managers/page.php
> +<html>
А где обязательные тэги `body`, `head`?

2023-04-09 09:28 UTC, nuberry commented on managers/index.php
> +<html>
А где обязательные тэги `body`, `head`?

2023-04-09 09:28 UTC, nuberry commented on managers/edit.php
> +<html>
А где обязательные тэги `body`, `head`?

2023-04-09 09:28 UTC, nuberry commented on get_db_info.php
> +    get_mysql_data($sql_request);
*Просто для справки, ничего не особо не переделываем*
Не самое лучшее решение. И нужна обработка данных от sql инъекций, большую часть ан себя забирает PDО и различные обертки в виде ORM

2023-04-09 09:28 UTC, nuberry commented on get_db_info.php
> +function edit_db_manager_data($update_params)
Раз нет возвращаемого значения, то можешь указать тип возвращаемого значения `:void`.

Также можешь подумать над указание типов для аргументов функции

2023-04-09 09:28 UTC, nuberry commented on get_db_info.php
> +function delete_db_manager_data($data){
Аналогично

2023-04-09 09:28 UTC, nuberry commented on get_db_info.php
> +function add_db_manager_data($new_data){
Аналогично

2023-04-09 09:28 UTC, nuberry commented on get_db_info.php
> +function get_mysql_data($sql_request)
Аналогично

2023-04-10 08:41 UTC, nuberry commented on managers/add.php
> +            <h1>Добавление записи менеджера</h1>
тут нарушение структуры.
1) `h1` не обязательно вставлять в `form`
2) Вставлять контент внутрь `table`, вне `tr>td` нельзя

2023-04-10 08:41 UTC, nuberry commented on applications/add.php
> +            <h1>Добавление новой заявки</h1>
Аналогично нарушение структуры

2023-04-10 08:41 UTC, nuberry commented on applications/edit.php
> +            </caption>
1) Нарушение структуры.
2) Речь про `caption` уже была в рамках страницы для менеджеров

2023-04-10 08:41 UTC, nuberry commented on get_db_info.php
> +    $correct_b_day_value = $db_b_day_data->format('m.d.Y');
Интересное решение.

На будущее для работ с датами лучше использовать DateTimeImmutable, оба используют один и тот же интерфейс `DateTimeInterface`

2023-04-10 08:41 UTC, nuberry commented on get_db_info.php
> +}
Я так понимаю неиспользуемая функция, со старым решением.
Давай удалим

2023-04-10 08:41 UTC, nuberry commented on get_db_info.php
> +    $sql_request = $sql_request_1_part . $sql_request_2_part . $sql_request_3_part;
Не особо нравится решение. Но пока оставь так.

2023-04-10 08:41 UTC, nuberry commented on get_db_info.php
> +    print $sql_request;
Удали

2023-04-10 08:41 UTC, nuberry commented on managers/edit.php
> +            </caption>
Аналогично

2023-04-10 08:41 UTC, nuberry commented on managers/page.php
> +    <h1>Информация о менеджере</h1>
Аналогично!

2023-04-10 08:41 UTC, nuberry commented on managers/index.php
> +  <h1>Список менеджеров</h1>
Вот тут хорошо

2023-04-10 08:41 UTC, nuberry commented on applications/page.php
> +    <h1>Информация о заявке</h1>
Аналогично

2023-04-11 10:14 UTC, merged